### ISSUE TITLE
Performance evaluation of other Paraphrasing Model and Techniques

### ISSUE THREAD

**Issue by ratulalahy** [ratulalahy/T5ParEvo#3]
**Run experiments with other paraphrasing model and compare the performance (accuracy + quantitative analysis) against T5ParEvo**
### Paraphrasing Model so far selected from 
**Huggingface:**
- [google/flan-t5-xxl](https://huggingface.co/google/flan-t5-xxl)
- [google/flan-t5-base](https://huggingface.co/google/flan-t5-base)
- [bigscience/mt0-xxl](https://huggingface.co/bigscience/mt0-xxl)
- [declare-lab/flan-alpaca-large](https://huggingface.co/declare-lab/flan-alpaca-large)
- [humarin/chatgpt_paraphraser_on_T5_base](https://huggingface.co/humarin/chatgpt_paraphraser_on_T5_base)
- [declare-lab/flan-alpaca-gpt4-xl](https://huggingface.co/declare-lab/flan-alpaca-gpt4-xl)
- [allenai/PRIMERA-arxiv](https://huggingface.co/allenai/PRIMERA-arxiv)
- [allenai/PRIMERA](https://huggingface.co/allenai/PRIMERA)
- [theojolliffe/bart-cnn-science](https://huggingface.co/theojolliffe/bart-cnn-science)
- [sharad/ParaphraseGPT](https://huggingface.co/sharad/ParaphraseGPT)
- [unikei/t5-base-split-and-rephrase](https://huggingface.co/unikei/t5-base-split-and-rephrase)
- [THUDM/WebGLM](https://huggingface.co/THUDM/WebGLM)

**Other Models to try:**
- ChatGpt2.0
- ChatGpt3.0
- ChatGpt3.5
- ChatFpt4.0

### Task List:
- [x] [allenai/PRIMERA-arxiv](https://huggingface.co/allenai/PRIMERA-arxiv)
- [x] [declare-lab/flan-alpaca-large](https://huggingface.co/declare-lab/flan-alpaca-large)
- [x] [bigscience/mt0-xxl](https://huggingface.co/bigscience/mt0-xxl)
- [ ] [theojolliffe/bart-cnn-science](https://huggingface.co/theojolliffe/bart-cnn-science)
- [x] [T5 base](https://huggingface.co/google/flan-t5-base)
- [x] [T5/Paws](https://huggingface.co/Vamsi/T5_Paraphrase_Paws)
- [ ] Experiment with Chatgpt Model 1
- [x] Analyze performance for all against attack
- [ ] Analyze quantitative analysis for all
